// src/components/Home.js
import React from 'react';

const Home = () => {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold text-center">Welcome to the Medical Image Analysis AI</h1>
      <p className="mt-4 text-center">
        Upload an image and get a textual description generated by our model.
      </p>
    </div>
  );
};

export default Home;
